name: Build Game

on:
  workflow_dispatch:
#   pull_request: {}
#   push: { branches: [main] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
        - ./
        unityVersion:
          - 2021.3.10f1
        targetPlatform:
#           - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
#           - StandaloneWindows64 # Build a Windows 64-bit standalone.
#           - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - WebGL # Build a HTML playable in browser
    steps:
      # Checkout
      - name: Checkout repository ⤵️
        uses: actions/checkout@v2
        with:
          lfs: false
          
      # Cache
      - name: Cache library 💾
        uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
            
      # Build
      - name: Build project 🚧
        uses: webbertakken/unity-builder@v0.10
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      # Output 
      - name: Upload build ⤴️
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
          # ls ./build --> StandaloneOSX/ StandaloneWindows64/ ... WebGL
          



  deployHTML:
    name: Deploy HTML App to itch.io 📤
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download builds ⤵️
        uses: actions/download-artifact@v2
        with:
          name: Build
      - name: Display structure of downloaded files
        run: ls -R
      - name: Deploy HTML build to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: gmtk2020
          ITCH_USER: avivajpeyi
          PACKAGE: WebGL
