name: Build Game

on:
  workflow_dispatch:
#   pull_request: {}
#   push: { branches: [main] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  checkLicense:
    name: Check for the Unity license ☑️
    runs-on: ubuntu-latest
    steps:
      - name: Fail - No license ☠️
        if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
        run: exit 1


  build:
    needs: checkLicense
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        unityVersion:
          - 2021.3.10f1
        targetPlatform:
#           - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
#           - StandaloneWindows64 # Build a Windows 64-bit standalone.
#           - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - WebGL # Build a HTML playable in browser
    steps:
      # Checkout
      - name: Checkout repository ⤵️
        uses: actions/checkout@v2
          
      # Cache
      - name: Cache library 💾
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-
            Library-
            
      # Build
      - name: Build project 🚧
        uses: game-ci/unity-builder@v2.1.1
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      # Output 
      - name: Upload build ⤴️
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
          # ls ./build --> StandaloneOSX/ StandaloneWindows64/ ... WebGL
          
#       # Deploy to itch
#       - name: Deploy to itch.io 📤
#         uses: josephbmanley/butler-publish-itchio-action@master
#         env:
#           BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
#           CHANNEL: ???
#           ITCH_GAME: ????
#           ITCH_USER: avivajpeyi
#           PACKAGE: build/${{ matrix.targetPlatform }}
        
          



  deployPages: # only for WebGL
    needs: build
    name: Deploy to Github Pages 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: build-WebGL
          path: build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build/WebGL



#   deployHTML: ## t
#     name: Deploy HTML App to itch.io 📤
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Download builds ⤵️
#         uses: actions/download-artifact@v2
#         with:
#           name: Build
#       - name: Display structure of downloaded files
#         run: ls -R
#       - name: Deploy HTML build to itch.io
#         uses: josephbmanley/butler-publish-itchio-action@master
#         env:
#           BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
#           CHANNEL: html5
#           ITCH_GAME: gmtk2020
#           ITCH_USER: avivajpeyi
#           PACKAGE: WebGL
